from app import *

db.create_all()

user1 = User(username='jolunney0',email = 'wlinsley0@bbc.co.uk')
user2 = User(username='hproback1',email = 'dcordeix1@odnoklassniki.ru')
user3 = User(username='hhonisch2',email = 'ghayward2@hc360.com')
user4 = User(username='dibbison3',email = 'cguilloud3@dion.ne.jp')
user5 = User(username='rwaiton4',email = 'estorm4@slashdot.org')
user6 = User(username='cwestlake5',email = 'lquarrell5@engadget.com')
user7 = User(username='gsalmen6',email = 'cmishaw6@about.me')
user8 = User(username='mkennelly7',email = 'bsemonin7@reuters.com')
user9 = User(username='bstockwell8',email = 'mhancox8@nhs.uk')
user10 = User(username='gbinge9',email = 'cweitzel9@miitbeian.gov.cn')
user11 = User(username='pheartya',email = 'tblackshawa@nationalgeographic.com')
user12 = User(username='blentschb',email = 'mnasebyb@hud.gov')
user13 = User(username='rterrenc',email = 'jlonghornc@wikipedia.org')
user14 = User(username='cliefd',email = 'gchampagned@domainmarket.com')
user15 = User(username='hcreaneye',email = 'hcosgrye@ox.ac.uk')
user16 = User(username='ltruesdalef',email = 'mcoughtreyf@symantec.com')
user17 = User(username='gpettitg',email = 'jstorkesg@mayoclinic.com')
user18 = User(username='tdowbigginh',email = 'dcullimoreh@smh.com.au')
user19 = User(username='mchazerandi',email = 'bbathoi@biblegateway.com')
user20 = User(username='ivellaj',email = 'fmcturleyj@cocolog-nifty.com')
user21 = User(username='tjaffreyk',email = 'dmacgorriek@histats.com')
user22 = User(username='rfoyl',email = 'gilyasl@lulu.com')
user23 = User(username='tprettyjohnm',email = 'wdamrellm@census.gov')
user24 = User(username='avoulsn',email = 'samphlettn@cdc.gov')
user25 = User(username='jspinko',email = 'nhargreaveso@economist.com')
user26 = User(username='gmollittp',email = 'bmaylerp@who.int')
user27 = User(username='dgrimeq',email = 'dfowkesq@google.co.jp')
user28 = User(username='fovingtonr',email = 'kcoyishr@alexa.com')
user29 = User(username='adimeos',email = 'knixs@opera.com')
user30 = User(username='vmckintyt',email = 'mmalinowskit@macromedia.com')
user31 = User(username='lsouleyu',email = 'hsillicku@godaddy.com')
user32 = User(username='dboutellierv',email = 'etunnav@google.com.br')
user33 = User(username='cjoontjesw',email = 'wleckiew@histats.com')
user34 = User(username='eamthorx',email = 'delwardx@unesco.org')
user35 = User(username='cknighty',email = 'gollerearnshawy@wp.com')
user36 = User(username='spaulleyz',email = 'cbatchelarz@people.com.cn')
user37 = User(username='rfairest10',email = 'jsturges10@4shared.com')
user38 = User(username='dpearse11',email = 'ameco11@rakuten.co.jp')
user39 = User(username='cwilfinger12',email = 'cnaulls12@unicef.org')
user40 = User(username='detchells13',email = 'fbalke13@digg.com')
user41 = User(username='hsprankling14',email = 'cbinney14@privacy.gov.au')
user42 = User(username='scobello15',email = 'gbrownett15@imgur.com')
user43 = User(username='cbauduin16',email = 'upizzie16@seattletimes.com')
user44 = User(username='nchesshire17',email = 'hmapplebeck17@yale.edu')
user45 = User(username='ogladebeck18',email = 'omachent18@wikia.com')
user46 = User(username='spetrecz19',email = 'escoyles19@yellowpages.com')
user47 = User(username='dmactrustam1a',email = 'gtape1a@latimes.com')
user48 = User(username='ajewer1b',email = 'zdunan1b@thetimes.co.uk')
user49 = User(username='vivanchenkov1c',email = 'cshailer1c@example.com')
user50 = User(username='boldacre1d',email = 'svockins1d@archive.org')

Ingredients1 = Ingredients(name='bagel',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='cup',amount=5)
Ingredients2 = Ingredients(name='batter',is_vegetarian = 0,is_vegan=0,is_gluten_free=1,unit='g',amount=3)
Ingredients3 = Ingredients(name='beans',is_vegetarian = 0,is_vegan=1,is_gluten_free=0,unit='tablespoon',amount=7)
Ingredients4 = Ingredients(name='beer',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='g',amount=5)
Ingredients5 = Ingredients(name='biscuit',is_vegetarian = 0,is_vegan=0,is_gluten_free=1,unit='teaspoon',amount=5)
Ingredients6 = Ingredients(name='bread',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='tablespoon',amount=5)
Ingredients7 = Ingredients(name='broth',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='g',amount=2)
Ingredients8 = Ingredients(name='burger',is_vegetarian = 1,is_vegan=0,is_gluten_free=0,unit='tablespoon',amount=6)
Ingredients9 = Ingredients(name='butter',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='kg',amount=9)
Ingredients10 = Ingredients(name='cake',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='cup',amount=8)
Ingredients11 = Ingredients(name='candy',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='tablespoon',amount=6)
Ingredients12 = Ingredients(name='caramel',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='cup',amount=3)
Ingredients13 = Ingredients(name='caviar',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='kg',amount=5)
Ingredients14 = Ingredients(name='cheese',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='kg',amount=1)
Ingredients15 = Ingredients(name='chili',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='tablespoon',amount=2)
Ingredients16 = Ingredients(name='chocolate',is_vegetarian = 0,is_vegan=0,is_gluten_free=0,unit='tablespoon',amount=5)
Ingredients17 = Ingredients(name='cider',is_vegetarian = 0,is_vegan=1,is_gluten_free=0,unit='g',amount=2)
Ingredients18 = Ingredients(name='cobbler',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='teaspoon',amount=9)
Ingredients19 = Ingredients(name='cocoa',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='g',amount=2)
Ingredients20 = Ingredients(name='coffee',is_vegetarian = 0,is_vegan=0,is_gluten_free=0,unit='tablespoon',amount=8)
Ingredients21 = Ingredients(name='cookie',is_vegetarian = 1,is_vegan=0,is_gluten_free=0,unit='teaspoon',amount=7)
Ingredients22 = Ingredients(name='cream',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='teaspoon',amount=8)
Ingredients23 = Ingredients(name='croissant',is_vegetarian = 1,is_vegan=1,is_gluten_free=1,unit='kg',amount=10)
Ingredients24 = Ingredients(name='crumble',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='tablespoon',amount=10)
Ingredients25 = Ingredients(name='cuisine',is_vegetarian = 0,is_vegan=0,is_gluten_free=1,unit='g',amount=3)
Ingredients26 = Ingredients(name='curd',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='tablespoon',amount=7)
Ingredients27 = Ingredients(name='dessert',is_vegetarian = 0,is_vegan=0,is_gluten_free=0,unit='teaspoon',amount=5)
Ingredients28 = Ingredients(name='dish',is_vegetarian = 1,is_vegan=1,is_gluten_free=1,unit='kg',amount=7)
Ingredients29 = Ingredients(name='drink',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='teaspoon',amount=1)
Ingredients30 = Ingredients(name='eggs',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='kg',amount=1)
Ingredients31 = Ingredients(name='entree',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='teaspoon',amount=2)
Ingredients32 = Ingredients(name='filet',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='tablespoon',amount=4)
Ingredients33 = Ingredients(name='fish',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='g',amount=1)
Ingredients34 = Ingredients(name='flour',is_vegetarian = 1,is_vegan=1,is_gluten_free=1,unit='teaspoon',amount=7)
Ingredients35 = Ingredients(name='foie gras',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='tablespoon',amount=6)
Ingredients36 = Ingredients(name='food',is_vegetarian = 0,is_vegan=1,is_gluten_free=0,unit='tablespoon',amount=2)
Ingredients37 = Ingredients(name='glaze',is_vegetarian = 0,is_vegan=0,is_gluten_free=1,unit='teaspoon',amount=8)
Ingredients38 = Ingredients(name='grill',is_vegetarian = 1,is_vegan=1,is_gluten_free=1,unit='teaspoon',amount=3)
Ingredients39 = Ingredients(name='hamburger',is_vegetarian = 0,is_vegan=1,is_gluten_free=1,unit='g',amount=3)
Ingredients40 = Ingredients(name='ice',is_vegetarian = 0,is_vegan=1,is_gluten_free=0,unit='g',amount=2)
Ingredients41 = Ingredients(name='juice',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='g',amount=8)
Ingredients42 = Ingredients(name='ketchup',is_vegetarian = 0,is_vegan=1,is_gluten_free=0,unit='cup',amount=7)
Ingredients43 = Ingredients(name='kitchen',is_vegetarian = 1,is_vegan=0,is_gluten_free=0,unit='g',amount=7)
Ingredients44 = Ingredients(name='lard',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='teaspoon',amount=3)
Ingredients45 = Ingredients(name='liquor',is_vegetarian = 1,is_vegan=0,is_gluten_free=1,unit='teaspoon',amount=3)
Ingredients46 = Ingredients(name='margarine',is_vegetarian = 0,is_vegan=1,is_gluten_free=0,unit='cup',amount=3)
Ingredients47 = Ingredients(name='marinade',is_vegetarian = 0,is_vegan=0,is_gluten_free=0,unit='tablespoon',amount=7)
Ingredients48 = Ingredients(name='mayo',is_vegetarian = 0,is_vegan=0,is_gluten_free=0,unit='teaspoon',amount=1)
Ingredients49 = Ingredients(name='mayonnaise',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='g',amount=3)
Ingredients50 = Ingredients(name='meat',is_vegetarian = 1,is_vegan=1,is_gluten_free=0,unit='g',amount=10)

recipe1 = Recipe(name='tincidunt in leo',serves = 1,difficulty='easy',time=100,views = 99,method = 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.In congue. Etiam justo. Etiam pretium iaculis justo.In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',user_id = 24)
recipe2 = Recipe(name='suspendisse potenti',serves = 1,difficulty='hard',time=60,views = 76,method = 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',user_id = 19)
recipe3 = Recipe(name='nulla justo',serves = 6,difficulty='medium',time=40,views = 1,method = 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectusPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',user_id = 4)
recipe4 = Recipe(name='ac est lacinia',serves = 3,difficulty='hard',time=60,views = 21,method = 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesqueQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purusPhasellus in felis. Donec semper sapien a libero. Nam duiProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',user_id = 32)
recipe5 = Recipe(name='ipsum aliquam non',serves = 4,difficulty='hard',time=80,views = 89,method = 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat duiMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',user_id = 40)
recipe6 = Recipe(name='pede posuere',serves = 1,difficulty='medium',time=50,views = 91,method = 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis estPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulumProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec semDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',user_id = 7)
recipe7 = Recipe(name='neque duis bibendum morbi',serves = 4,difficulty='hard',time=100,views = 58,method = 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non maurisMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel semSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctusCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',user_id = 16)
recipe8 = Recipe(name='non mauris morbi',serves = 6,difficulty='hard',time=90,views = 62,method = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat variusInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',user_id = 2)
recipe9 = Recipe(name='sapien a libero',serves = 4,difficulty='hard',time=50,views = 63,method = 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felisFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel semSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectusPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctusCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',user_id = 41)
recipe10 = Recipe(name='tincidunt ante vel ipsum',serves = 4,difficulty='medium',time=50,views = 23,method = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potentiNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non maurisMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',user_id = 16)
recipe11 = Recipe(name='vestibulum ante ipsum',serves = 2,difficulty='hard',time=10,views = 73,method = 'In congue. Etiam justo. Etiam pretium iaculis justoIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',user_id = 9)
recipe12 = Recipe(name='donec ut mauris',serves = 4,difficulty='easy',time=90,views = 43,method = 'Fusce consequat. Nulla nisl. Nunc nislDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',user_id = 31)
recipe13 = Recipe(name='tristique fusce congue diam',serves = 3,difficulty='easy',time=10,views = 74,method = 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felisFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel semSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctusCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus musEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',user_id = 26)
recipe14 = Recipe(name='augue vel accumsan',serves = 5,difficulty='easy',time=10,views = 42,method = 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellusNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisiCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesqueQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purusPhasellus in felis. Donec semper sapien a libero. Nam dui.',user_id = 15)
recipe15 = Recipe(name='ac enim in',serves = 2,difficulty='medium',time=30,views = 38,method = 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementumIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpisSed ante. Vivamus tortor. Duis mattis egestas metus.Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibhQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',user_id = 35)
recipe16 = Recipe(name='donec diam neque',serves = 4,difficulty='hard',time=60,views = 59,method = 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac nequeDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectusSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut eratCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',user_id = 30)
recipe17 = Recipe(name='sagittis nam congue risus',serves = 3,difficulty='easy',time=40,views = 85,method = 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectusSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut eratCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',user_id = 46)
recipe18 = Recipe(name='justo sit',serves = 3,difficulty='medium',time=10,views = 28,method = 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut eratCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placeratPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',user_id = 18)
recipe19 = Recipe(name='eget orci',serves = 2,difficulty='medium',time=20,views = 94,method = 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nislAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',user_id = 44)
recipe20 = Recipe(name='habitasse platea',serves = 6,difficulty='easy',time=120,views = 47,method = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis liberoNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra ede ac diam. Cras pellentesque volutpat dui.',user_id = 47)
recipe21 = Recipe(name='duis faucibus',serves = 3,difficulty='easy',time=30,views = 73,method = 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',user_id = 26)
recipe22 = Recipe(name='posuere nonummy integer non',serves = 1,difficulty='easy',time=100,views = 43,method = 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felisFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel semSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',user_id = 9)
recipe23 = Recipe(name='vel nisl duis',serves = 2,difficulty='easy',time=20,views = 83,method = 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felisFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectusPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',user_id = 7)
recipe24 = Recipe(name='justo maecenas rhoncus aliquam',serves = 2,difficulty='medium',time=100,views = 90,method = 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justoAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.Sed ante. Vivamus tortor. Duis mattis egestas metusAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',user_id = 4)
recipe25 = Recipe(name='quis justo maecenas',serves = 4,difficulty='easy',time=60,views = 20,method = 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibhQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpatIn congue. Etiam justo. Etiam pretium iaculis justo.',user_id = 15)
recipe26 = Recipe(name='placerat praesent blandit nam',serves = 3,difficulty='easy',time=110,views = 79,method = 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel semSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctusCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',user_id = 38)
recipe27 = Recipe(name='sodales sed tincidunt eu',serves = 5,difficulty='easy',time=20,views = 45,method = 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec semDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velitDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',user_id = 41)
recipe28 = Recipe(name='at diam nam',serves = 5,difficulty='hard',time=40,views = 73,method = 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulumProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',user_id = 40)
recipe29 = Recipe(name='amet turpis elementum',serves = 1,difficulty='easy',time=50,views = 50,method = 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis esthasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulumProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velitDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac nequeDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',user_id = 15)
recipe30 = Recipe(name='orci luctus',serves = 1,difficulty='easy',time=100,views = 95,method = 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elitProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nislAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentumCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis estPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',user_id = 12)
recipe31 = Recipe(name='est quam pharetra magna',serves = 1,difficulty='hard',time=10,views = 100,method = 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallisDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.',user_id = 3)
recipe32 = Recipe(name='in ante',serves = 3,difficulty='easy',time=110,views = 41,method = 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat variusInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisiNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',user_id = 48)
recipe33 = Recipe(name='lorem ipsum',serves = 2,difficulty='medium',time=60,views = 17,method = 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felisFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectusPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',user_id = 7)
recipe34 = Recipe(name='ut at',serves = 1,difficulty='hard',time=50,views = 40,method = 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, semFusce consequat. Nulla nisl. Nunc nisl.Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementumIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justoAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpisSed ante. Vivamus tortor. Duis mattis egestas metus.',user_id = 5)
recipe35 = Recipe(name='magnis dis',serves = 4,difficulty='medium',time=10,views = 27,method = 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibhIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat duiMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',user_id = 21)
recipe36 = Recipe(name='justo sit amet',serves = 4,difficulty='easy',time=120,views = 40,method = 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pedeMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.Fusce consequat. Nulla nisl. Nunc nisl.',user_id = 22)
recipe37 = Recipe(name='erat tortor sollicitudin mi',serves = 2,difficulty='medium',time=40,views = 52,method = 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibhIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',user_id = 10)
recipe38 = Recipe(name='eu nibh quisque',serves = 4,difficulty='hard',time=80,views = 86,method = 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac nequeDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectusSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',user_id = 43)
recipe39 = Recipe(name='ultrices posuere cubilia curae',serves = 4,difficulty='easy',time=80,views = 20,method = 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus musEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',user_id = 31)
recipe40 = Recipe(name='auctor gravida',serves = 5,difficulty='hard',time=120,views = 28,method = 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pedeMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.Fusce consequat. Nulla nisl. Nunc nislDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementumIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justoAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',user_id = 12)
recipe41 = Recipe(name='sapien urna pretium nisl',serves = 2,difficulty='medium',time=100,views = 52,method = 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentumCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',user_id = 18)
recipe42 = Recipe(name='etiam faucibus',serves = 4,difficulty='easy',time=10,views = 74,method = 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non maurisMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felisFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel semSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectusPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',user_id = 35)
recipe43 = Recipe(name='nam nulla',serves = 4,difficulty='medium',time=40,views = 62,method = 'Sed ante. Vivamus tortor. Duis mattis egestas metus.Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibhQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, erosVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',user_id = 6)
recipe44 = Recipe(name='rutrum ac',serves = 1,difficulty='hard',time=50,views = 71,method = 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectusPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctusCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus musEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida semPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',user_id = 8)
recipe45 = Recipe(name='nam dui proin',serves = 1,difficulty='hard',time=90,views = 24,method = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectusVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncusMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis liberoNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',user_id = 5)
recipe46 = Recipe(name='tortor id nulla ultrices',serves = 3,difficulty='hard',time=30,views = 32,method = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectusVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',user_id = 15)
recipe47 = Recipe(name='sapien dignissim vestibulum',serves = 6,difficulty='easy',time=110,views = 46,method = 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisiNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacusCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',user_id = 33)
recipe48 = Recipe(name='elit proin risus',serves = 5,difficulty='hard',time=30,views = 68,method = 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nislAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis estPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulumProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec semDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',user_id = 42)
recipe49 = Recipe(name='viverra eget congue eget',serves = 2,difficulty='medium',time=40,views = 58,method = 'In congue. Etiam justo. Etiam pretium iaculis justoIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',user_id = 1)
recipe50 = Recipe(name='nonummy maecenas tincidunt lacus',serves = 3,difficulty='easy',time=120,views = 95,method = 'Fusce consequat. Nulla nisl. Nunc nisl.Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementumIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',user_id = 24)

db.session.add(user1)
db.session.add(user2)
db.session.add(user3)
db.session.add(user4)
db.session.add(user5)
db.session.add(user6)
db.session.add(user7)
db.session.add(user8)
db.session.add(user9)
db.session.add(user10)
db.session.add(user11)
db.session.add(user12)
db.session.add(user13)
db.session.add(user14)
db.session.add(user15)
db.session.add(user16)
db.session.add(user17)
db.session.add(user18)
db.session.add(user19)
db.session.add(user20)
db.session.add(user21)
db.session.add(user22)
db.session.add(user23)
db.session.add(user24)
db.session.add(user25)
db.session.add(user26)
db.session.add(user27)
db.session.add(user28)
db.session.add(user29)
db.session.add(user30)
db.session.add(user31)
db.session.add(user32)
db.session.add(user33)
db.session.add(user34)
db.session.add(user35)
db.session.add(user36)
db.session.add(user37)
db.session.add(user38)
db.session.add(user39)
db.session.add(user40)
db.session.add(user41)
db.session.add(user42)
db.session.add(user43)
db.session.add(user44)
db.session.add(user45)
db.session.add(user46)
db.session.add(user47)
db.session.add(user48)
db.session.add(user49)
db.session.add(user50)

db.session.add(Ingredients1)
db.session.add(Ingredients2)
db.session.add(Ingredients3)
db.session.add(Ingredients4)
db.session.add(Ingredients5)
db.session.add(Ingredients6)
db.session.add(Ingredients7)
db.session.add(Ingredients8)
db.session.add(Ingredients9)
db.session.add(Ingredients10)
db.session.add(Ingredients11)
db.session.add(Ingredients12)
db.session.add(Ingredients13)
db.session.add(Ingredients14)
db.session.add(Ingredients15)
db.session.add(Ingredients16)
db.session.add(Ingredients17)
db.session.add(Ingredients18)
db.session.add(Ingredients19)
db.session.add(Ingredients20)
db.session.add(Ingredients21)
db.session.add(Ingredients22)
db.session.add(Ingredients23)
db.session.add(Ingredients24)
db.session.add(Ingredients25)
db.session.add(Ingredients26)
db.session.add(Ingredients27)
db.session.add(Ingredients28)
db.session.add(Ingredients29)
db.session.add(Ingredients30)
db.session.add(Ingredients31)
db.session.add(Ingredients32)
db.session.add(Ingredients33)
db.session.add(Ingredients34)
db.session.add(Ingredients35)
db.session.add(Ingredients36)
db.session.add(Ingredients37)
db.session.add(Ingredients38)
db.session.add(Ingredients39)
db.session.add(Ingredients40)
db.session.add(Ingredients41)
db.session.add(Ingredients42)
db.session.add(Ingredients43)
db.session.add(Ingredients44)
db.session.add(Ingredients45)
db.session.add(Ingredients46)
db.session.add(Ingredients47)
db.session.add(Ingredients48)
db.session.add(Ingredients49)
db.session.add(Ingredients50)

db.session.add(recipe1)
db.session.add(recipe2)
db.session.add(recipe3)
db.session.add(recipe4)
db.session.add(recipe5)
db.session.add(recipe6)
db.session.add(recipe7)
db.session.add(recipe8)
db.session.add(recipe9)
db.session.add(recipe10)
db.session.add(recipe11)
db.session.add(recipe12)
db.session.add(recipe13)
db.session.add(recipe14)
db.session.add(recipe15)
db.session.add(recipe16)
db.session.add(recipe17)
db.session.add(recipe18)
db.session.add(recipe19)
db.session.add(recipe20)
db.session.add(recipe21)
db.session.add(recipe22)
db.session.add(recipe23)
db.session.add(recipe24)
db.session.add(recipe25)
db.session.add(recipe26)
db.session.add(recipe27)
db.session.add(recipe28)
db.session.add(recipe29)
db.session.add(recipe30)
db.session.add(recipe31)
db.session.add(recipe32)
db.session.add(recipe33)
db.session.add(recipe34)
db.session.add(recipe35)
db.session.add(recipe36)
db.session.add(recipe37)
db.session.add(recipe38)
db.session.add(recipe39)
db.session.add(recipe40)
db.session.add(recipe41)
db.session.add(recipe42)
db.session.add(recipe43)
db.session.add(recipe44)
db.session.add(recipe45)
db.session.add(recipe46)
db.session.add(recipe47)
db.session.add(recipe48)
db.session.add(recipe49)
db.session.add(recipe50)

recipe1.ingredients.append(Ingredients44)
recipe2.ingredients.append(Ingredients21)
recipe3.ingredients.append(Ingredients33)
recipe4.ingredients.append(Ingredients23)
recipe5.ingredients.append(Ingredients10)
recipe6.ingredients.append(Ingredients36)
recipe7.ingredients.append(Ingredients43)
recipe8.ingredients.append(Ingredients44)
recipe9.ingredients.append(Ingredients24)
recipe10.ingredients.append(Ingredients36)
recipe11.ingredients.append(Ingredients8)
recipe12.ingredients.append(Ingredients29)
recipe13.ingredients.append(Ingredients24)
recipe14.ingredients.append(Ingredients24)
recipe15.ingredients.append(Ingredients35)
recipe16.ingredients.append(Ingredients38)
recipe17.ingredients.append(Ingredients43)
recipe18.ingredients.append(Ingredients33)
recipe19.ingredients.append(Ingredients16)
recipe20.ingredients.append(Ingredients39)
recipe21.ingredients.append(Ingredients45)
recipe22.ingredients.append(Ingredients42)
recipe23.ingredients.append(Ingredients11)
recipe24.ingredients.append(Ingredients27)
recipe25.ingredients.append(Ingredients31)
recipe26.ingredients.append(Ingredients32)
recipe27.ingredients.append(Ingredients22)
recipe28.ingredients.append(Ingredients22)
recipe29.ingredients.append(Ingredients37)
recipe30.ingredients.append(Ingredients16)
recipe31.ingredients.append(Ingredients33)
recipe32.ingredients.append(Ingredients23)
recipe33.ingredients.append(Ingredients46)
recipe34.ingredients.append(Ingredients31)
recipe35.ingredients.append(Ingredients29)
recipe36.ingredients.append(Ingredients46)
recipe37.ingredients.append(Ingredients17)
recipe38.ingredients.append(Ingredients40)
recipe39.ingredients.append(Ingredients22)
recipe40.ingredients.append(Ingredients3)
recipe41.ingredients.append(Ingredients3)
recipe42.ingredients.append(Ingredients2)
recipe43.ingredients.append(Ingredients31)
recipe44.ingredients.append(Ingredients20)
recipe45.ingredients.append(Ingredients7)
recipe46.ingredients.append(Ingredients27)
recipe47.ingredients.append(Ingredients2)
recipe48.ingredients.append(Ingredients47)
recipe49.ingredients.append(Ingredients30)
recipe50.ingredients.append(Ingredients32)
recipe1.ingredients.append(Ingredients42)
recipe2.ingredients.append(Ingredients29)
recipe3.ingredients.append(Ingredients44)
recipe4.ingredients.append(Ingredients3)
recipe5.ingredients.append(Ingredients9)
recipe6.ingredients.append(Ingredients44)
recipe7.ingredients.append(Ingredients12)
recipe8.ingredients.append(Ingredients17)
recipe9.ingredients.append(Ingredients28)
recipe10.ingredients.append(Ingredients28)
recipe11.ingredients.append(Ingredients3)
recipe12.ingredients.append(Ingredients48)
recipe13.ingredients.append(Ingredients7)
recipe14.ingredients.append(Ingredients38)
recipe15.ingredients.append(Ingredients25)
recipe16.ingredients.append(Ingredients39)
recipe17.ingredients.append(Ingredients47)
recipe18.ingredients.append(Ingredients21)
recipe19.ingredients.append(Ingredients35)
recipe20.ingredients.append(Ingredients47)
recipe21.ingredients.append(Ingredients10)
recipe22.ingredients.append(Ingredients25)
recipe23.ingredients.append(Ingredients25)
recipe24.ingredients.append(Ingredients47)
recipe25.ingredients.append(Ingredients1)
recipe26.ingredients.append(Ingredients23)
recipe27.ingredients.append(Ingredients47)
recipe28.ingredients.append(Ingredients19)
recipe29.ingredients.append(Ingredients40)
recipe30.ingredients.append(Ingredients15)
recipe31.ingredients.append(Ingredients24)
recipe32.ingredients.append(Ingredients11)
recipe33.ingredients.append(Ingredients31)
recipe34.ingredients.append(Ingredients20)
recipe35.ingredients.append(Ingredients23)
recipe36.ingredients.append(Ingredients43)
recipe37.ingredients.append(Ingredients1)
recipe38.ingredients.append(Ingredients29)
recipe39.ingredients.append(Ingredients50)
recipe40.ingredients.append(Ingredients31)
recipe41.ingredients.append(Ingredients22)
recipe42.ingredients.append(Ingredients48)
recipe43.ingredients.append(Ingredients46)
recipe44.ingredients.append(Ingredients18)
recipe45.ingredients.append(Ingredients7)
recipe46.ingredients.append(Ingredients16)
recipe47.ingredients.append(Ingredients28)
recipe48.ingredients.append(Ingredients27)
recipe49.ingredients.append(Ingredients25)
recipe50.ingredients.append(Ingredients23)
recipe1.ingredients.append(Ingredients44)
recipe2.ingredients.append(Ingredients26)
recipe3.ingredients.append(Ingredients24)
recipe4.ingredients.append(Ingredients9)
recipe5.ingredients.append(Ingredients3)
recipe6.ingredients.append(Ingredients44)
recipe7.ingredients.append(Ingredients43)
recipe8.ingredients.append(Ingredients7)
recipe9.ingredients.append(Ingredients23)
recipe10.ingredients.append(Ingredients20)
recipe11.ingredients.append(Ingredients12)
recipe12.ingredients.append(Ingredients45)
recipe13.ingredients.append(Ingredients22)
recipe14.ingredients.append(Ingredients26)
recipe15.ingredients.append(Ingredients24)
recipe16.ingredients.append(Ingredients5)
recipe17.ingredients.append(Ingredients29)
recipe18.ingredients.append(Ingredients10)
recipe19.ingredients.append(Ingredients31)
recipe20.ingredients.append(Ingredients22)
recipe21.ingredients.append(Ingredients21)
recipe22.ingredients.append(Ingredients10)
recipe23.ingredients.append(Ingredients7)
recipe24.ingredients.append(Ingredients43)
recipe25.ingredients.append(Ingredients25)
recipe26.ingredients.append(Ingredients23)
recipe27.ingredients.append(Ingredients48)
recipe28.ingredients.append(Ingredients22)
recipe29.ingredients.append(Ingredients48)
recipe30.ingredients.append(Ingredients42)
recipe31.ingredients.append(Ingredients45)
recipe32.ingredients.append(Ingredients29)
recipe33.ingredients.append(Ingredients47)
recipe34.ingredients.append(Ingredients24)
recipe35.ingredients.append(Ingredients13)
recipe36.ingredients.append(Ingredients8)
recipe37.ingredients.append(Ingredients13)
recipe38.ingredients.append(Ingredients44)
recipe39.ingredients.append(Ingredients41)
recipe40.ingredients.append(Ingredients23)
recipe41.ingredients.append(Ingredients22)
recipe42.ingredients.append(Ingredients5)
recipe43.ingredients.append(Ingredients32)
recipe44.ingredients.append(Ingredients37)
recipe45.ingredients.append(Ingredients31)
recipe46.ingredients.append(Ingredients23)
recipe47.ingredients.append(Ingredients12)
recipe48.ingredients.append(Ingredients13)
recipe49.ingredients.append(Ingredients9)
recipe50.ingredients.append(Ingredients11)
recipe34.ingredients.append(Ingredients35)
recipe30.ingredients.append(Ingredients11)
recipe20.ingredients.append(Ingredients50)
recipe41.ingredients.append(Ingredients33)
recipe40.ingredients.append(Ingredients19)
recipe23.ingredients.append(Ingredients22)
recipe46.ingredients.append(Ingredients19)
recipe21.ingredients.append(Ingredients12)
recipe19.ingredients.append(Ingredients27)
recipe27.ingredients.append(Ingredients24)
recipe23.ingredients.append(Ingredients40)
recipe6.ingredients.append(Ingredients34)
recipe38.ingredients.append(Ingredients7)
recipe48.ingredients.append(Ingredients43)
recipe5.ingredients.append(Ingredients13)
recipe33.ingredients.append(Ingredients19)
recipe42.ingredients.append(Ingredients45)
recipe50.ingredients.append(Ingredients11)
recipe38.ingredients.append(Ingredients28)
recipe23.ingredients.append(Ingredients15)
recipe46.ingredients.append(Ingredients33)
recipe36.ingredients.append(Ingredients23)
recipe38.ingredients.append(Ingredients44)
recipe7.ingredients.append(Ingredients11)
recipe14.ingredients.append(Ingredients25)
recipe15.ingredients.append(Ingredients23)
recipe25.ingredients.append(Ingredients2)
recipe35.ingredients.append(Ingredients32)
recipe17.ingredients.append(Ingredients25)
recipe17.ingredients.append(Ingredients6)
recipe9.ingredients.append(Ingredients4)
recipe19.ingredients.append(Ingredients7)
recipe3.ingredients.append(Ingredients21)
recipe43.ingredients.append(Ingredients12)
recipe6.ingredients.append(Ingredients21)
recipe4.ingredients.append(Ingredients24)
recipe40.ingredients.append(Ingredients29)
recipe39.ingredients.append(Ingredients12)
recipe41.ingredients.append(Ingredients4)
recipe15.ingredients.append(Ingredients7)
recipe35.ingredients.append(Ingredients20)
recipe3.ingredients.append(Ingredients5)
recipe27.ingredients.append(Ingredients27)
recipe15.ingredients.append(Ingredients11)
recipe21.ingredients.append(Ingredients15)
recipe16.ingredients.append(Ingredients26)
recipe16.ingredients.append(Ingredients41)
recipe25.ingredients.append(Ingredients25)
recipe40.ingredients.append(Ingredients8)
recipe47.ingredients.append(Ingredients34)
recipe15.ingredients.append(Ingredients49)
recipe28.ingredients.append(Ingredients7)
recipe49.ingredients.append(Ingredients5)
recipe30.ingredients.append(Ingredients33)
recipe29.ingredients.append(Ingredients9)
recipe18.ingredients.append(Ingredients31)
recipe41.ingredients.append(Ingredients28)
recipe15.ingredients.append(Ingredients35)
recipe39.ingredients.append(Ingredients46)
recipe23.ingredients.append(Ingredients16)
recipe31.ingredients.append(Ingredients3)
recipe38.ingredients.append(Ingredients45)
recipe4.ingredients.append(Ingredients7)
recipe21.ingredients.append(Ingredients5)
recipe44.ingredients.append(Ingredients11)
recipe45.ingredients.append(Ingredients14)
recipe3.ingredients.append(Ingredients33)
recipe45.ingredients.append(Ingredients10)
recipe42.ingredients.append(Ingredients21)
recipe21.ingredients.append(Ingredients4)
recipe17.ingredients.append(Ingredients13)
recipe38.ingredients.append(Ingredients2)
recipe36.ingredients.append(Ingredients31)
recipe3.ingredients.append(Ingredients5)
recipe24.ingredients.append(Ingredients10)
recipe4.ingredients.append(Ingredients17)
recipe35.ingredients.append(Ingredients47)
recipe47.ingredients.append(Ingredients34)
recipe4.ingredients.append(Ingredients35)
recipe42.ingredients.append(Ingredients45)
recipe44.ingredients.append(Ingredients30)
recipe36.ingredients.append(Ingredients45)
recipe35.ingredients.append(Ingredients42)
recipe32.ingredients.append(Ingredients25)
recipe11.ingredients.append(Ingredients34)
recipe28.ingredients.append(Ingredients38)
recipe8.ingredients.append(Ingredients43)
recipe30.ingredients.append(Ingredients15)
recipe32.ingredients.append(Ingredients13)
recipe18.ingredients.append(Ingredients41)
recipe32.ingredients.append(Ingredients16)
recipe38.ingredients.append(Ingredients31)
recipe18.ingredients.append(Ingredients37)
recipe16.ingredients.append(Ingredients28)
recipe7.ingredients.append(Ingredients37)
recipe49.ingredients.append(Ingredients44)
recipe35.ingredients.append(Ingredients26)
recipe30.ingredients.append(Ingredients17)
recipe5.ingredients.append(Ingredients32)
recipe43.ingredients.append(Ingredients37)
recipe24.ingredients.append(Ingredients1)
recipe40.ingredients.append(Ingredients21)
recipe34.ingredients.append(Ingredients43)
recipe20.ingredients.append(Ingredients34)
recipe48.ingredients.append(Ingredients37)
recipe17.ingredients.append(Ingredients16)
recipe44.ingredients.append(Ingredients49)
recipe16.ingredients.append(Ingredients8)
recipe16.ingredients.append(Ingredients49)
recipe44.ingredients.append(Ingredients3)
recipe23.ingredients.append(Ingredients10)
recipe31.ingredients.append(Ingredients37)
recipe47.ingredients.append(Ingredients29)
recipe47.ingredients.append(Ingredients8)
recipe9.ingredients.append(Ingredients21)
recipe22.ingredients.append(Ingredients1)
recipe42.ingredients.append(Ingredients36)
recipe37.ingredients.append(Ingredients8)
recipe39.ingredients.append(Ingredients3)
recipe29.ingredients.append(Ingredients7)
recipe9.ingredients.append(Ingredients1)
recipe42.ingredients.append(Ingredients40)
recipe40.ingredients.append(Ingredients46)
recipe20.ingredients.append(Ingredients33)
recipe14.ingredients.append(Ingredients24)
recipe24.ingredients.append(Ingredients26)
recipe3.ingredients.append(Ingredients42)
recipe20.ingredients.append(Ingredients24)
recipe44.ingredients.append(Ingredients28)
recipe38.ingredients.append(Ingredients12)
recipe25.ingredients.append(Ingredients2)
recipe18.ingredients.append(Ingredients40)
recipe17.ingredients.append(Ingredients47)
recipe44.ingredients.append(Ingredients12)
recipe47.ingredients.append(Ingredients1)
recipe48.ingredients.append(Ingredients10)
recipe16.ingredients.append(Ingredients17)
recipe16.ingredients.append(Ingredients33)
recipe14.ingredients.append(Ingredients24)
recipe9.ingredients.append(Ingredients3)
recipe46.ingredients.append(Ingredients34)
recipe33.ingredients.append(Ingredients8)
recipe29.ingredients.append(Ingredients24)
recipe37.ingredients.append(Ingredients34)
recipe37.ingredients.append(Ingredients32)
recipe2.ingredients.append(Ingredients10)
recipe24.ingredients.append(Ingredients25)
recipe39.ingredients.append(Ingredients8)
recipe36.ingredients.append(Ingredients23)
recipe50.ingredients.append(Ingredients1)

db.session.commit()